language: java
jdk:
  - oraclejdk8
env:
  matrix:
    - PROFILE=ci
    - PROFILE=spring41-next
    - PROFILE=spring42
    - PROFILE=spring42-next
    - PROFILE=spring43
    - PROFILE=spring43-next
    - PROFILE=spring5-next
    - PROFILE=external-cassandra CASSANDRA_VERSION=2.2.6
    - PROFILE=external-cassandra CASSANDRA_VERSION=3.0.7
    - PROFILE=external-cassandra CASSANDRA_VERSION=3.2
    - PROFILE=external-cassandra CASSANDRA_VERSION=3.3
    - PROFILE=external-cassandra CASSANDRA_VERSION=3.4
    - PROFILE=external-cassandra CASSANDRA_VERSION=3.5
    - PROFILE=external-cassandra CASSANDRA_VERSION=3.6
    - PROFILE=external-cassandra CASSANDRA_VERSION=3.7
cache:
  directories:
    - $HOME/.m2
    - 'download'
sudo: false
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
install: if [ ! -z ${CASSANDRA_VERSION} ]; then ./setup-cassandra.sh; fi;
script: mvn clean install -P${PROFILE} -Dmaven.javadoc.skip=true
